services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "9000:9000"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network: