services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "9000:80"  # Mapeando a porta 80 do contêiner para a porta 9000 no host
    networks:
      - app-network

networks:
  app-network: