services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
    ports:
      - port: 8000

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80
    ports:
      - port: 9000  # Mapeando a porta 80 do contêiner para a porta 9000 no host

networks:
  - name: app-network
