services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000

  - type: web
    name: frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80
